#!/usr/bin/env python
'''Test of NI-DM SPM export tool

To run the test, copy the NIDM turtle file 'spm_nidm.ttl' obtained by exporting
the results of example001 (as specified in 'examples/spm/example001') in a
directory named spmexport' under 'test' and from the command line call:

python test/TestSPMResultDataModel.py

@author: Camille Maumet <c.m.j.maumet@warwick.ac.uk>, Satrajit Ghosh
@copyright: University of Warwick 2014
'''
import unittest
import os
from rdflib.graph import Graph
import logging
import glob

# Save debug info in a log file (debug.log)
logging.basicConfig(filename='debug.log', level=logging.DEBUG, filemode='w')
logger = logging.getLogger(__name__)
logger.info(' ---------- Debug log ----------')

import sys
RELPATH = os.path.dirname(os.path.abspath(__file__))

# Add nidm common testing code folder to python path
NIDM_DIR = os.path.join(RELPATH, "nidm")

# In TravisCI the nidm repository will be created as a subtree, however locally
# the nidm directory will be accessed directly
logging.debug(NIDM_DIR)
if not os.path.isdir(NIDM_DIR):
    NIDM_DIR = os.path.join(RELPATH, "..", "nidm")
    logging.debug(NIDM_DIR)

NIDM_RESULTS_DIR = os.path.join(NIDM_DIR, "nidm", "nidm-results")
sys.path.append(os.path.join(NIDM_RESULTS_DIR, "test"))

from TestResultDataModel import TestResultDataModel
from TestCommons import *
from CheckConsistency import *
from ddt import ddt, data

TEST_DIR = os.path.dirname(os.path.abspath(__file__))
# Find all test examples to be compared with ground truth
test_files = glob.glob(os.path.join(TEST_DIR, 'spmexport', 'ex*', '*.ttl'))
# For test name readability remove path to test file
test_files = [x.replace(TEST_DIR, "") for x in test_files]
logging.info("Test files:\n\t" + "\n\t".join(test_files))


@ddt
class TestSPMResultsDataModel(unittest.TestCase, TestResultDataModel):

    def setUp(self):
        self.my_execption = ""

        # Display log messages in console
        logging.basicConfig(
            level=logging.DEBUG,
            format='%(asctime)s - %(levelname)s - %(message)s')

        # Retreive owl file for NIDM-Results
        owl_file = os.path.join(NIDM_RESULTS_DIR, 'terms', 'nidm-results.owl')
        # Retreive imported owl files from NIDM-Results
        owl_imports = glob.glob(os.path.join(
            os.path.dirname(owl_file),
            os.pardir, os.pardir, "imports", '*.ttl'))

        TestResultDataModel.setUp(self, owl_file, owl_imports, test_files,
                                  TEST_DIR, NIDM_RESULTS_DIR)

    @data(*test_files)
    def test_class_consistency_with_owl(self, ttl):
        """
        Test: Check that the classes used in the ttl file are defined in the
        owl file.
        """
        ex = self.ex_graphs[ttl]
        ex.owl.check_class_names(ex.graph, ex.name, True)

    @data(*test_files)
    def test_attributes_consistency_with_owl(self, ttl):
        """
        Test: Check that the attributes used in the ttl file comply with their
        definition (range, domain) specified in the owl file.
        """
        ex = self.ex_graphs[ttl]
        ex.owl.check_attributes(ex.graph, ex.name, True)

    @data(*test_files)
    def test_examples_match_ground_truth(self, ttl):
        """
        Test03: Comparing that the ttl file generated by SPM and the expected
        ttl file (generated manually) are identical
        """

        ex = self.ex_graphs[ttl]

        for gt_file in ex.gt_ttl_files:
            logging.info("Ground truth ttl: " + gt_file)

            # RDF obtained by the ground truth export
            gt = Graph()
            gt.parse(gt_file, format='turtle')

            self.compare_full_graphs(gt, ex.graph, ex.exact_comparison, True)


if __name__ == '__main__':
    unittest.main()
